config/routes.rb
CrStyleSearch::Application.routes.draw do

  root :to => 'pictures#index'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'

  get '/profiles/new', controller: 'profiles', action: 'new', as: 'new_profile'
  post '/profiles', controller: 'profiles', action: 'create'

  get '/profiles', controller: 'profiles', action: 'index', as: 'profiles'
  get '/profiles/:id', controller: 'profiles', action: 'show', as: 'profile'

  get '/profiles/:id/edit', controller: 'profiles', action: 'edit', as: 'edit_profile'
  put '/profiles/:id', controller: 'profiles', action: 'update'

  delete '/profiles/:id', controller: 'profiles', action: 'destroy'

  get '/professionals/new', controller: 'professionals', action: 'new', as: 'new_professional'
  post '/professionals', controller: 'professionals', action: 'create'

  get '/professionals', controller: 'professionals', action: 'index', as: 'professionals'
  get '/professionals/:id', controller: 'professionals', action: 'show', as: 'professional'

  get '/professionals/:id/edit', controller: 'professionals', action: 'edit', as: 'edit_professional'
  put '/professionals/:id', controller: 'professionals', action: 'update'

  delete '/professionals/:id', controller: 'professionals', action: 'destroy'

  get '/requirements/new', controller: 'requirements', action: 'new', as: 'new_requirement'
  post '/requirements', controller: 'requirements', action: 'create'

  get '/requirements', controller: 'requirements', action: 'index', as: 'requirements'
  get '/requirements/:id', controller: 'requirements', action: 'show', as: 'requirement'

  get '/requirements/:id/edit', controller: 'requirements', action: 'edit', as: 'edit_requirement'
  put '/requirements/:id', controller: 'requirements', action: 'update'

  delete '/requirements/:id', controller: 'requirements', action: 'destroy'

  get '/pictures/new', controller: 'pictures', action: 'new', as: 'new_picture'
  post '/pictures', controller: 'pictures', action: 'create'

  get '/pictures', controller: 'pictures', action: 'index', as: 'pictures'
  get '/pictures/:id', controller: 'pictures', action: 'show', as: 'picture'

  get '/pictures/:id/edit', controller: 'pictures', action: 'edit', as: 'edit_picture'
  put '/pictures/:id', controller: 'pictures', action: 'update'

  delete '/pictures/:id', controller: 'pictures', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/profile.rb
class Profile < ActiveRecord::Base

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find_by_id(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new
    @profile.picture_id = params[:picture_id]
    @profile.user_id = params[:user_id]
    @profile.professional_id = params[:professional_id]
    @profile.requirement_id = params[:requirement_id]
    
    if @profile.save
            redirect_to profiles_url
          else
      render 'new'
    end
  end

  def edit
    @profile = Profile.find_by_id(params[:id])
  end

  def update
    @profile = Profile.find_by_id(params[:id])
    @profile.picture_id = params[:picture_id]
    @profile.user_id = params[:user_id]
    @profile.professional_id = params[:professional_id]
    @profile.requirement_id = params[:requirement_id]
    
    if @profile.save
            redirect_to profiles_url
          else
      render 'edit'
    end
  end

  def destroy
    @profile = Profile.find_by_id(params[:id])
    @profile.destroy
        redirect_to profiles_url
      end
end

app/views/profiles/edit.html.erb
<h1>Editing Profile #<%= @profile.id %></h1>


<%= form_tag(profile_url(@profile), method: 'put') do %>

  <div>
    <%= label_tag :picture_id %><br />
    <%= number_field_tag :picture_id, @profile.picture_id %>
  </div>

  <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id, @profile.user_id %>
  </div>

  <div>
    <%= label_tag :professional_id %><br />
    <%= number_field_tag :professional_id, @profile.professional_id %>
  </div>

  <div>
    <%= label_tag :requirement_id %><br />
    <%= number_field_tag :requirement_id, @profile.requirement_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Profile" %>
  </div>

<% end %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<p><%= link_to 'Add a New Profile', new_profile_url %></p>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>User</th>
      <th>Professional</th>
      <th>Requirement</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @profiles.each do |profile| %>
    <tr>
      <td><%= profile.picture_id %></td>
      <td><%= profile.user_id %></td>
      <td><%= profile.professional_id %></td>
      <td><%= profile.requirement_id %></td>
  
      <td><%= link_to 'Show', profile_url(profile) %></td>
      <td><%= link_to 'Edit', edit_profile_url(profile) %></td>
      <td><%= link_to 'Destroy', profile_url(profile), method: 'delete', data: { confirm: "Do you really want to delete this profile?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h1>New Profile</h1>


<%= form_tag(profiles_url, method: 'post') do %>


  <div>
    <%= label_tag :picture_id %><br />
    <%= number_field_tag :picture_id %>
  </div>

    <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id %>
  </div>

    <div>
    <%= label_tag :professional_id %><br />
    <%= number_field_tag :professional_id %>
  </div>

    <div>
    <%= label_tag :requirement_id %><br />
    <%= number_field_tag :requirement_id %>
  </div>

  
  <div>
    <%= submit_tag "Create Profile" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<h1>Profile #<%= @profile.id %></h1>

<p>
  <b>Picture:</b>
  <%= @profile.picture_id %>
</p>

<p>
  <b>User:</b>
  <%= @profile.user_id %>
</p>

<p>
  <b>Professional:</b>
  <%= @profile.professional_id %>
</p>

<p>
  <b>Requirement:</b>
  <%= @profile.requirement_id %>
</p>