config/routes.rb
CrStyleSearch::Application.routes.draw do

  root :to => 'pictures#index'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'

  get '/profiles/new', controller: 'profiles', action: 'new', as: 'new_profile'
  post '/profiles', controller: 'profiles', action: 'create'

  get '/profiles', controller: 'profiles', action: 'index', as: 'profiles'
  get '/profiles/:id', controller: 'profiles', action: 'show', as: 'profile'

  get '/profiles/:id/edit', controller: 'profiles', action: 'edit', as: 'edit_profile'
  put '/profiles/:id', controller: 'profiles', action: 'update'

  delete '/profiles/:id', controller: 'profiles', action: 'destroy'

  get '/professionals/new', controller: 'professionals', action: 'new', as: 'new_professional'
  post '/professionals', controller: 'professionals', action: 'create'

  get '/professionals', controller: 'professionals', action: 'index', as: 'professionals'
  get '/professionals/:id', controller: 'professionals', action: 'show', as: 'professional'

  get '/professionals/:id/edit', controller: 'professionals', action: 'edit', as: 'edit_professional'
  put '/professionals/:id', controller: 'professionals', action: 'update'

  delete '/professionals/:id', controller: 'professionals', action: 'destroy'

  get '/requirements/new', controller: 'requirements', action: 'new', as: 'new_requirement'
  post '/requirements', controller: 'requirements', action: 'create'

  get '/requirements', controller: 'requirements', action: 'index', as: 'requirements'
  get '/requirements/:id', controller: 'requirements', action: 'show', as: 'requirement'

  get '/requirements/:id/edit', controller: 'requirements', action: 'edit', as: 'edit_requirement'
  put '/requirements/:id', controller: 'requirements', action: 'update'

  delete '/requirements/:id', controller: 'requirements', action: 'destroy'

  get '/pictures/new', controller: 'pictures', action: 'new', as: 'new_picture'
  post '/pictures', controller: 'pictures', action: 'create'

  get '/pictures', controller: 'pictures', action: 'index', as: 'pictures'
  get '/pictures/:id', controller: 'pictures', action: 'show', as: 'picture'

  get '/pictures/:id/edit', controller: 'pictures', action: 'edit', as: 'edit_picture'
  put '/pictures/:id', controller: 'pictures', action: 'update'

  delete '/pictures/:id', controller: 'pictures', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    if @user.save
           session[:user_id] = @user.id
           redirect_to users_url
          else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    if @user.save
            redirect_to users_url
          else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
        redirect_to users_url
      end
end

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name, @user.first_name %>
  </div>

  <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name, @user.last_name %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
<div>
    <%= label_tag :password_confirmation %><br />
    <%= password_field_tag :password_confirmation %>
  </div>

  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
  
      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name %>
  </div>

    <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name %>
  </div>

    <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
<div>
    <%= label_tag :password_confirmation %><br />
    <%= password_field_tag :password_confirmation %>
  </div>


  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>