config/routes.rb
CrStyleSearch::Application.routes.draw do

  root :to => 'pictures#index'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'

  get '/profiles/new', controller: 'profiles', action: 'new', as: 'new_profile'
  post '/profiles', controller: 'profiles', action: 'create'

  get '/profiles', controller: 'profiles', action: 'index', as: 'profiles'
  get '/profiles/:id', controller: 'profiles', action: 'show', as: 'profile'

  get '/profiles/:id/edit', controller: 'profiles', action: 'edit', as: 'edit_profile'
  put '/profiles/:id', controller: 'profiles', action: 'update'

  delete '/profiles/:id', controller: 'profiles', action: 'destroy'

  get '/professionals/new', controller: 'professionals', action: 'new', as: 'new_professional'
  post '/professionals', controller: 'professionals', action: 'create'

  get '/professionals', controller: 'professionals', action: 'index', as: 'professionals'
  get '/professionals/:id', controller: 'professionals', action: 'show', as: 'professional'

  get '/professionals/:id/edit', controller: 'professionals', action: 'edit', as: 'edit_professional'
  put '/professionals/:id', controller: 'professionals', action: 'update'

  delete '/professionals/:id', controller: 'professionals', action: 'destroy'

  get '/requirements/new', controller: 'requirements', action: 'new', as: 'new_requirement'
  post '/requirements', controller: 'requirements', action: 'create'

  get '/requirements', controller: 'requirements', action: 'index', as: 'requirements'
  get '/requirements/:id', controller: 'requirements', action: 'show', as: 'requirement'

  get '/requirements/:id/edit', controller: 'requirements', action: 'edit', as: 'edit_requirement'
  put '/requirements/:id', controller: 'requirements', action: 'update'

  delete '/requirements/:id', controller: 'requirements', action: 'destroy'

  get '/pictures/new', controller: 'pictures', action: 'new', as: 'new_picture'
  post '/pictures', controller: 'pictures', action: 'create'

  get '/pictures', controller: 'pictures', action: 'index', as: 'pictures'
  get '/pictures/:id', controller: 'pictures', action: 'show', as: 'picture'

  get '/pictures/:id/edit', controller: 'pictures', action: 'edit', as: 'edit_picture'
  put '/pictures/:id', controller: 'pictures', action: 'update'

  delete '/pictures/:id', controller: 'pictures', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find_by_id(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new
    @picture.caption = params[:caption]
    @picture.add_pic = params[:add_pic]
    @picture.source = params[:source]
    
    if @picture.save
            redirect_to pictures_url
          else
      render 'new'
    end
  end

  def edit
    @picture = Picture.find_by_id(params[:id])
  end

  def update
    @picture = Picture.find_by_id(params[:id])
    @picture.caption = params[:caption]
    @picture.add_pic = params[:add_pic]
    @picture.source = params[:source]
    
    if @picture.save
            redirect_to pictures_url
          else
      render 'edit'
    end
  end

  def destroy
    @picture = Picture.find_by_id(params[:id])
    @picture.destroy
        redirect_to pictures_url
      end
end

app/views/pictures/edit.html.erb
<h1>Editing Picture #<%= @picture.id %></h1>


<%= form_tag(picture_url(@picture), method: 'put') do %>

  <div>
    <%= label_tag :caption %><br />
    <%= text_area_tag :caption, @picture.caption %>
  </div>

  <div>
    <%= label_tag :add_pic %><br />
    <%= check_box_tag :add_pic, @picture.add_pic? %>
  </div>

  <div>
    <%= label_tag :source %><br />
    <%= text_field_tag :source, @picture.source %>
  </div>

  
  <div>
    <%= submit_tag "Update Picture" %>
  </div>

<% end %>

app/views/pictures/index.html.erb
<h1>Pictures</h1>

<p><%= link_to 'Add a New Picture', new_picture_url %></p>

<!-- <table>
  <thead>
 -->   <!--  <tr>
      <th>Caption</th>
      <th>Add pic</th>
      <th>Source</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
 -->
  <body>

  <% @pictures.each do |picture| %>

<ul style="list-style: none;">

      <li><%= picture.caption %></li>
      <li><%= check_box_tag picture.add_pic %></li>
      <li><%= image_tag picture.source, :width => 300 %></li>


      <li><%= link_to 'Show', picture_url(picture) %></li>
      <li><%= link_to 'Edit', edit_picture_url(picture) %></li>
      <li><%= link_to 'Destroy', picture_url(picture), method: 'delete', data: { confirm: "Do you really want to delete this picture?" } %></li>

    </tr>
</ul>

  <% end %>
  </body>
</table>

app/views/pictures/new.html.erb
<h1>New Picture</h1>


<%= form_tag(pictures_url, method: 'post') do %>


  <div>
    <%= label_tag :caption %><br />
    <%= text_area_tag :caption %>
  </div>

    <div>
    <%= label_tag :add_pic %><br />
    <%= check_box_tag :add_pic? %>
  </div>

    <div>
    <%= label_tag :source %><br />
    <%= text_field_tag :source %>
  </div>

  
  <div>
    <%= submit_tag "Create Picture" %>
  </div>
<% end %>

app/views/pictures/show.html.erb
<h1>Picture #<%= @picture.id %></h1>

<p>
  <b>Caption:</b>
  <%= @picture.caption %>
</p>

<p>
  <b>Add pic:</b>
  <%= @picture.add_pic %>
</p>

<p>
  <b>Source:</b>
  <img src="<%= @picture.source %>">
</p>