config/routes.rb
CrStyleSearch::Application.routes.draw do

  root :to => 'pictures#index'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'

  get '/profiles/new', controller: 'profiles', action: 'new', as: 'new_profile'
  post '/profiles', controller: 'profiles', action: 'create'

  get '/profiles', controller: 'profiles', action: 'index', as: 'profiles'
  get '/profiles/:id', controller: 'profiles', action: 'show', as: 'profile'

  get '/profiles/:id/edit', controller: 'profiles', action: 'edit', as: 'edit_profile'
  put '/profiles/:id', controller: 'profiles', action: 'update'

  delete '/profiles/:id', controller: 'profiles', action: 'destroy'

  get '/professionals/new', controller: 'professionals', action: 'new', as: 'new_professional'
  post '/professionals', controller: 'professionals', action: 'create'

  get '/professionals', controller: 'professionals', action: 'index', as: 'professionals'
  get '/professionals/:id', controller: 'professionals', action: 'show', as: 'professional'

  get '/professionals/:id/edit', controller: 'professionals', action: 'edit', as: 'edit_professional'
  put '/professionals/:id', controller: 'professionals', action: 'update'

  delete '/professionals/:id', controller: 'professionals', action: 'destroy'

  get '/requirements/new', controller: 'requirements', action: 'new', as: 'new_requirement'
  post '/requirements', controller: 'requirements', action: 'create'

  get '/requirements', controller: 'requirements', action: 'index', as: 'requirements'
  get '/requirements/:id', controller: 'requirements', action: 'show', as: 'requirement'

  get '/requirements/:id/edit', controller: 'requirements', action: 'edit', as: 'edit_requirement'
  put '/requirements/:id', controller: 'requirements', action: 'update'

  delete '/requirements/:id', controller: 'requirements', action: 'destroy'

  get '/pictures/new', controller: 'pictures', action: 'new', as: 'new_picture'
  post '/pictures', controller: 'pictures', action: 'create'

  get '/pictures', controller: 'pictures', action: 'index', as: 'pictures'
  get '/pictures/:id', controller: 'pictures', action: 'show', as: 'picture'

  get '/pictures/:id/edit', controller: 'pictures', action: 'edit', as: 'edit_picture'
  put '/pictures/:id', controller: 'pictures', action: 'update'

  delete '/pictures/:id', controller: 'pictures', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Crstylesearch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Crstylesearch</a>
        <div class="nav-collapse">
          <ul class="nav">

            <li><%= link_to "Home", "/" %></li>
            <li><%= link_to "Users", "/users" %></li>
            <li><%= link_to "Pictures", "/pictures" %></li>
            <li><%= link_to "Requirements", "/requirements" %></li>
            <li><%= link_to "Professionals", "/professionals" %></li>
            <li><%= link_to "Profiles", "/profiles" %></li>
            <li><a href="#about">About</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

      <% if session[:user_id].present? %>
        <p>Welcome back, <%= User.find(session[:user_id]).email %>. <%= link_to "Sign Out", session_url, method: 'delete' %></p>
      <% else %>
       <p><%= link_to "Sign Up", new_user_url %> or <%= link_to "Sign In", new_session_url %></p>
     <% end %>

  <p><%= notice %></p>

  <div class="container">

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
    <% end %>

    <%= yield %>

    <hr>

    <footer>
      <p>&copy; Company 2012</p>
    </footer>

  </div>

</body>
</html>